### PR TITLE
Fix P120 and P128; orphans

### PR DESCRIPTION
**Pull request by joshmoore**
These 2 plates need .screen files (if possible)

cc: @simleo

### CODE REVIEW

**Comment by eleanorwilliams** [comment]
P120 does not exist, instead the directory name is p120.  There is a .screen file in idr0004-thorpe-rad52/screens/p120.screen.
We want the plate name to appear as P120 in omero but currently it appears as p120.  
When the .screen file for P128 is created, we need to delete the existing screen in demo1 and re-import the whole screen and check that the P120 name has been correctly assigned.

**Comment by joshmoore** [comment]
There are no data files in P128, @eleanorwilliams. Do you know if they are somewhere else?

**Comment by eleanorwilliams** [comment]
They are in /idr/filesets/idr0004-thorpe-rad52/Rad52_old/P128. One directory above all the other data directories.

**Comment by joshmoore** [comment]
@simleo : oh dear. This looks like it'll be fun:

```
[jamoore@narwhal generate_screens]$ ls /idr/filesets/idr0004-thorpe-rad52/Rad52_old/P128/
10b  10e    10g    11d  11g  12d  1c  1g  2e  2h  3e    3g  4e  4h    5b-3  5d  5h  6d  6g  7c  7f  8b  8e  8h  9d  9g
10c  10e-2  11c    11e  12b  12e  1D  2c  2f  3c  3f    4c  4f  4h-2  5c    5e  6b  6e  6h  7d  7g  8c  8f  9b  9e
10d  10f    11c-2  11f  12c  12f  1e  2d  2g  3d  3f-2  4d  4g  5b-2  5c-2  5g  6c  6f  7b  7e  7h  8d  8g  9c  9f
```

**Comment by joshmoore** [comment]
In!

**Pull request merged**
