### PR TITLE
Adding cmpo ur ls to bulk annotation files

### PR DESCRIPTION
**Pull request by eleanorwilliams**
Added links to CMPO to all ontology term accession columns in bulk annotation files. 

Concerned about the following which don't have the same number of columns throughout the file even before I started adding URLs (used awk -F"," '{print NF}' idr0008-screenB-annotation.csv | sort | uniq -c).
idr0002-heriche-condensation/screenA/idr0002-screenA-annotation.csv
idr0003-breker-plasticity/screenA/idr0003-screenA-annotation.csv
idr0006-fong-nuclearbodies/screenA/idr0006-screenA-annotation.csv
idr0009-simpson-secretion/screenA/idr0009-screenA-annotation.csv 

Also note the following studies had no change to the annotation.csv files as they have no ontology links.
idr0004-thorpe-rad52
idr0005-toret-adhesion/screenA 
idr0005-toret-adhesion/screenB
idr0007-srikumar-sumo

### CODE REVIEW

**Comment by manics** [comment]
It looks like the mismatch in number of commas was because some fields contained a quoted string including `,`, e.g. `Gene Identifier` in `idr0009-simpson-secretion/screenA/idr0009-screenA-annotation.csv`:

```
: df=pandas.read_csv('idr0009-simpson-secretion/screenA/idr0009-screenA-annotation.csv',mangle_dupe_cols=False,index_col=False)

: z=df.applymap(lambda x: isinstance(x,str) and ',' in x)

: z.apply(sum,axis=0)
Plate                                                           0
Plate Group                                                     0
Well Number                                                     0
Well                                                            0
siRNA Identifier                                                0
Gene Identifier %% url=http://www.ensembl.org/id/%s            28
Gene Symbol Ens81                                               0
Gene Symbol Ens61                                               0
Control Type                                                    0
Control Comments                                                0
Quality Control                                                 0
Comments                                                        0
Deviation                                                       0
Cell Number                                                     0
Valid Plates                                                    0
% Inhibitor                                                     0
% Accelerator                                                   0
Transcripts Hit                                                 0
Transcript Identifiers                                          0
Gene In Validation Screen                                       0
Validated Strong Inhibitor Gene Hit                             0
Phenotype                                                       0
Ontology Term                                                   0
Ontology Term Accession %% url=http://www.ebi.ac.uk/cmpo/%s     0
dtype: int64

: z=df['Gene Identifier %% url=http://www.ensembl.org/id/%s'].apply(lambda x: isinstance(x,str) and ',' in x)

: df['Gene Identifier %% url=http://www.ensembl.org/id/%s'][z]
57308    ENSG00000013441,ENSG00000240344
57692    ENSG00000013441,ENSG00000240344
58076    ENSG00000013441,ENSG00000240344
58460    ENSG00000013441,ENSG00000240344
58844    ENSG00000013441,ENSG00000240344
72488    ENSG00000013441,ENSG00000240344
72872    ENSG00000013441,ENSG00000240344
73256    ENSG00000013441,ENSG00000240344
73640    ENSG00000013441,ENSG00000240344
74024    ENSG00000013441,ENSG00000240344
74408    ENSG00000013441,ENSG00000240344
88629    ENSG00000069018,ENSG00000254809
89013    ENSG00000069018,ENSG00000254809
89397    ENSG00000069018,ENSG00000254809
89781    ENSG00000069018,ENSG00000254809
90165    ENSG00000069018,ENSG00000254809
94168    ENSG00000069018,ENSG00000254809
94552    ENSG00000069018,ENSG00000254809
94936    ENSG00000069018,ENSG00000254809
95320    ENSG00000069018,ENSG00000254809
95704    ENSG00000069018,ENSG00000254809
96088    ENSG00000069018,ENSG00000254809
96666    ENSG00000069018,ENSG00000254809
97050    ENSG00000069018,ENSG00000254809
97434    ENSG00000069018,ENSG00000254809
97818    ENSG00000069018,ENSG00000254809
98202    ENSG00000069018,ENSG00000254809
98586    ENSG00000069018,ENSG00000254809
Name: Gene Identifier %% url=http://www.ensembl.org/id/%s, dtype: object
```

**Comment by manics** [comment]
This would need testing, but I think if you add 
```
  split: ","
```
to the `Gene Identifier` column definition in the `bulkmap-config.yml` (e.g. see https://github.com/openmicroscopy/idr-metadata/pull/1/files#diff-8039b2b3279dd77d50772e338dd15951R33) they should be automatically split into two separate entries in the MapAnnotation.

**Comment by eleanorwilliams** [comment]
Removed commas within columns for idr0009, idr0002 and idr0003.  
Leaving idr0006-screenA-annotation.csv as the extra commas I was counting were within the 'Description' column, where bits of text are separated by commas or commas are in chemical compound names.  Simon has already 'fixed' this file so it should be ok.

**Comment by joshmoore** [comment]
Closing & re-opening to make use of gh-32.

**Comment by joshmoore** [comment]
Travis is green! Also, all imports barring rohn went flawlessly. :thumbsup:

**Pull request merged**
