### PR TITLE
Add unit tests to Travis

### PR DESCRIPTION
**Pull request by simleo**
Adds an "all_tests" driver and and a line to run it from Travis

### CODE REVIEW

**Comment by joshmoore** [comment]
Something seems odd:

```
======================================================================
ERROR: test_file_pattern (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_file_pattern
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/python/2.7.9/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/openmicroscopy/idr-metadata/test/test_file_pattern.py", line 3, in <module>
    import pyidr.file_pattern as fp
ImportError: No module named pyidr.file_pattern
======================================================================
ERROR: test_screenio (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_screenio
Traceback (most recent call last):
  File "/opt/python/2.7.9/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/opt/python/2.7.9/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/travis/build/openmicroscopy/idr-metadata/test/test_screenio.py", line 6, in <module>
    from pyidr.screenio import ScreenWriter, ScreenReader, ScreenError
ImportError: No module named pyidr.screenio
----------------------------------------------------------------------
Ran 2 tests in 0.001s
FAILED (errors=2)
The command "python test/all_tests.py" exited with 0.
cache.2
store build cache
0.01s1.44schanges detected, packing new archive
FAILED: tar -Pzcf /home/travis/.casher/push.tgz 
tar: Cowardly refusing to create an empty archive
Try `tar --help' or `tar --usage' for more information.
uploading archive
failed to upload cache
curl: Can't open '/home/travis/.casher/push.tgz'!
curl: try 'curl --help' or 'curl --manual' for more information
Done. Your build exited with 0.
```

**Comment by simleo** [comment]
I forgot to install the package. What's disturbing is that Travis marked the build as passing despite the test failures

**Comment by simleo** [comment]
Seems OK now

**Comment by joshmoore** [comment]
Nice

```
----------------------------------------------------------------------
Ran 20 tests in 0.026s
OK
```

:+1: Keepin' @sbesson happy...

**Pull request merged**
