### PR TITLE
Add sysgro mineotaur properties file

### PR DESCRIPTION
**Pull request by manics**
See https://github.com/manics/Mineotaur/blob/docker/DOCKER.md for testing

### CODE REVIEW

**Comment by joshmoore** [comment]
Happy to just merge unless you want testing, @manics. Longer term, this looks like a prime candidate for having imported via `metadata.py` as an annotation that can be consumed later.

**Comment by manics** [comment]
It'd be nice, but al apps would need to understand the annotation, and also accept a host/user/session-id.

**Comment by joshmoore** [comment]
I would think only a single app would need to understand its own properties annotation (with its own namespace)

**Comment by manics** [comment]
OK. I opened this PR so there's a record of what's been done, happy for you to merge or put on-hold as you wish.

**Pull request merged**
