### PR TITLE
Sysgro feature/ROI import scripts

### PR DESCRIPTION
**Pull request by manics**
Originally from https://github.com/manics/idr-data-munging
In future these should be refactored so they can be used as a more general feature/roi upload tool with other screens.

Note this depends on https://github.com/manics/omero-features/commit/249015c0ffa396ae45f06789336ec7cac3f6a9a2

### CODE REVIEW

**Comment by joshmoore** [comment]
> Note this depends on manics/omero-features@249015c

Shall we get that in too then?

**Comment by manics** [comment]
Submodule? Or merge and tag omero-features?

**Comment by joshmoore** [comment]
I was thinking merge & tag.

**Comment by manics** [comment]
Merged, go ahead and tag it with whatever makes sense.

**Pull request merged**
